In [36]:
import numpy as np
import pandas as pd
from math import sqrt
dot_data = [[2.7810836,2.550537003,0],
	[1.465489372,2.362125076,0],
	[3.396561688,4.400293529,0],
	[1.38807019,1.850220317,0],
	[3.06407232,3.005305973,0],
	[7.627531214,2.759262235,1],
	[5.332441248,2.088626775,1],
	[6.922596716,1.77106367,1],
	[8.675418651,-0.242068655,1],
	[7.673756466,3.508563011,1]]
dot_data = pd.DataFrame(dot_data)
dot_data.columns = ['x','y','status']

          x         y  status
0  2.781084  2.550537       0
1  1.465489  2.362125       0
2  3.396562  4.400294       0
3  1.388070  1.850220       0
4  3.064072  3.005306       0
5  7.627531  2.759262       1
6  5.332441  2.088627       1
7  6.922597  1.771064       1
8  8.675419 -0.242069       1
9  7.673756  3.508563       1

In [37]:
class KNN:
    def euclidean_distance(self, new_data, data):
        dis_x = []
        dis_y = []
        dis_s = []
        dis_index = []
        dis = []
        dis = np.array(dis)
        data_1 = data.values
        
        for i in range(len(data)):
            dis_x.append(round(((data_1[i][0] - new_data[0])**2),2))
            dis_y.append(round(((data_1[i][1] - new_data[1])**2),2))
            dis_s.append(int(data_1[i][2]))
            dis_index.append(i)
        
        dis_x = np.array(dis_x)
        dis_y = np.array(dis_y)
        dis_s = np.array(dis_s)
        dis_index = np.array(dis_index)
        
        dis = np.sqrt(dis_x + dis_y)
        data_frame = pd.DataFrame([dis, dis_s, dis_index])
        data_frame.index = ['distance', 'status', 'index']
        data_frame.sort_values(by = 'distance',axis = 1, inplace = True)
        return data_frame
    
    def find(self, data, k):
        #n_data = []
        #array = data.values
        #for i in range(k):
        #    n_data.append(array[1][i])
        index = []
        index = data.values
        index = np.array(index)
        index = index.astype(int)
        for i in range(k):
            print(dot_data.loc[index[i][2],['x','y','status']])

In [38]:
m = KNN()
dot = [3,1]
dot = np.array(dot)
a = m.euclidean_distance(dot, dot_data)
k = m.find(a,3)

x         3.396562
y         4.400294
status    0.000000
Name: 2, dtype: float64
x         2.781084
y         2.550537
status    0.000000
Name: 0, dtype: float64
x         3.064072
y         3.005306
status    0.000000
Name: 4, dtype: float64